apiVersion: v1
kind: Service
metadata:
  name: sample-api-service
spec:
  type: LoadBalancer  # or NodePort for local clusters
  selector:
    app: sample-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
